name: build & deploy it as a static website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 想要“最近更新时间”等 git 日志相关信息，需要拉取全部提交记录

      - name: Install pnpm, then install dependencies immediately
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x # latest
          # cache: pnpm

      - name: Build the project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm run docs:build
          > book/.vuepress/dist/.nojekyll

      - name: Deploy to Aliyun ECS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.ALIYUN_HOST }}
          REMOTE_USER: ${{ secrets.ALIYUN_USER }}
          ARGS: "-avzr --delete"
          SOURCE: book/.vuepress/dist/
          TARGET: ${{ secrets.ALIYUN_DEPLOY_TARGET }}
